{{- if .Values.paymentReconcileWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lago-alpha.fullname" . }}-payment-reconcile-worker
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment-reconcile-worker
spec:
  replicas: {{ .Values.paymentReconcileWorker.replicas }}
  selector:
    matchLabels:
      {{- include "lago-alpha.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: payment-reconcile-worker
  template:
    metadata:
      labels:
        {{- include "lago-alpha.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: payment-reconcile-worker
        {{- with .Values.paymentReconcileWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "lago-alpha.reloaderAnnotations" (dict "root" . "includeDatabase" true) | nindent 8 }}
        {{- with .Values.paymentReconcileWorker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "lago-alpha.serviceAccountName.paymentReconcileWorker" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: payment-reconcile-worker
          image: "{{ default .Values.api.image.repository .Values.paymentReconcileWorker.image.repository }}:{{ default .Values.api.image.tag .Values.paymentReconcileWorker.image.tag }}"
          imagePullPolicy: {{ .Values.paymentReconcileWorker.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          {{- include "lago-alpha.runtimeEnvFrom" . | nindent 10 }}
          env:
            - name: RUN_API_SERVER
              value: "false"
            - name: RUN_REPLAY_WORKER
              value: "false"
            - name: RUN_REPLAY_DISPATCHER
              value: "false"
            - name: RUN_BILLING_CONNECTION_CHECK_WORKER
              value: "false"
            - name: RUN_BILLING_CONNECTION_CHECK_SCHEDULER
              value: "false"
            - name: RUN_PAYMENT_RECONCILE_WORKER
              value: "true"
            - name: RUN_PAYMENT_RECONCILE_SCHEDULER
              value: "false"
            - name: RUN_DUNNING_WORKER
              value: "false"
            - name: RUN_DUNNING_SCHEDULER
              value: "false"
          resources:
            {{- toYaml .Values.paymentReconcileWorker.resources | nindent 12 }}
{{- end }}
