/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WorkspaceSetupRouteImport } from "./routes/workspace-setup"
import { Route as WorkspaceAccessRouteImport } from "./routes/workspace-access"
import { Route as UsageEventsRouteImport } from "./routes/usage-events"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as ReplayOperationsRouteImport } from "./routes/replay-operations"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as PaymentOperationsRouteImport } from "./routes/payment-operations"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as InvoiceExplainabilityRouteImport } from "./routes/invoice-explainability"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as CustomerOnboardingRouteImport } from "./routes/customer-onboarding"
import { Route as ControlPlaneRouteImport } from "./routes/control-plane"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SubscriptionsIndexRouteImport } from "./routes/subscriptions/index"
import { Route as PricingIndexRouteImport } from "./routes/pricing/index"
import { Route as PaymentsIndexRouteImport } from "./routes/payments/index"
import { Route as InvoicesIndexRouteImport } from "./routes/invoices/index"
import { Route as DunningIndexRouteImport } from "./routes/dunning/index"
import { Route as CustomersIndexRouteImport } from "./routes/customers/index"
import { Route as SubscriptionsNewRouteImport } from "./routes/subscriptions/new"
import { Route as SubscriptionsIdRouteImport } from "./routes/subscriptions/$id"
import { Route as PaymentsIdRouteImport } from "./routes/payments/$id"
import { Route as InvoicesIdRouteImport } from "./routes/invoices/$id"
import { Route as InviteTokenRouteImport } from "./routes/invite/$token"
import { Route as DunningIdRouteImport } from "./routes/dunning/$id"
import { Route as CustomersNewRouteImport } from "./routes/customers/new"
import { Route as CustomersExternalIdRouteImport } from "./routes/customers/$externalId"
import { Route as PricingTaxesIndexRouteImport } from "./routes/pricing/taxes/index"
import { Route as PricingPlansIndexRouteImport } from "./routes/pricing/plans/index"
import { Route as PricingMetricsIndexRouteImport } from "./routes/pricing/metrics/index"
import { Route as PricingCouponsIndexRouteImport } from "./routes/pricing/coupons/index"
import { Route as PricingAddOnsIndexRouteImport } from "./routes/pricing/add-ons/index"
import { Route as PricingTaxesNewRouteImport } from "./routes/pricing/taxes/new"
import { Route as PricingTaxesIdRouteImport } from "./routes/pricing/taxes/$id"
import { Route as PricingPlansNewRouteImport } from "./routes/pricing/plans/new"
import { Route as PricingPlansIdRouteImport } from "./routes/pricing/plans/$id"
import { Route as PricingMetricsNewRouteImport } from "./routes/pricing/metrics/new"
import { Route as PricingMetricsIdRouteImport } from "./routes/pricing/metrics/$id"
import { Route as PricingCouponsNewRouteImport } from "./routes/pricing/coupons/new"
import { Route as PricingCouponsIdRouteImport } from "./routes/pricing/coupons/$id"
import { Route as PricingAddOnsNewRouteImport } from "./routes/pricing/add-ons/new"
import { Route as PricingAddOnsIdRouteImport } from "./routes/pricing/add-ons/$id"

const WorkspaceSetupRoute = WorkspaceSetupRouteImport.update({
  id: "/workspace-setup",
  path: "/workspace-setup",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAccessRoute = WorkspaceAccessRouteImport.update({
  id: "/workspace-access",
  path: "/workspace-access",
  getParentRoute: () => rootRouteImport,
} as any)
const UsageEventsRoute = UsageEventsRouteImport.update({
  id: "/usage-events",
  path: "/usage-events",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayOperationsRoute = ReplayOperationsRouteImport.update({
  id: "/replay-operations",
  path: "/replay-operations",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOperationsRoute = PaymentOperationsRouteImport.update({
  id: "/payment-operations",
  path: "/payment-operations",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceExplainabilityRoute = InvoiceExplainabilityRouteImport.update({
  id: "/invoice-explainability",
  path: "/invoice-explainability",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOnboardingRoute = CustomerOnboardingRouteImport.update({
  id: "/customer-onboarding",
  path: "/customer-onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPlaneRoute = ControlPlaneRouteImport.update({
  id: "/control-plane",
  path: "/control-plane",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: "/subscriptions/",
  path: "/subscriptions/",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: "/pricing/",
  path: "/pricing/",
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: "/payments/",
  path: "/payments/",
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: "/invoices/",
  path: "/invoices/",
  getParentRoute: () => rootRouteImport,
} as any)
const DunningIndexRoute = DunningIndexRouteImport.update({
  id: "/dunning/",
  path: "/dunning/",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: "/customers/",
  path: "/customers/",
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsNewRoute = SubscriptionsNewRouteImport.update({
  id: "/subscriptions/new",
  path: "/subscriptions/new",
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: "/subscriptions/$id",
  path: "/subscriptions/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIdRoute = PaymentsIdRouteImport.update({
  id: "/payments/$id",
  path: "/payments/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: "/invoices/$id",
  path: "/invoices/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const DunningIdRoute = DunningIdRouteImport.update({
  id: "/dunning/$id",
  path: "/dunning/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: "/customers/new",
  path: "/customers/new",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersExternalIdRoute = CustomersExternalIdRouteImport.update({
  id: "/customers/$externalId",
  path: "/customers/$externalId",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingTaxesIndexRoute = PricingTaxesIndexRouteImport.update({
  id: "/pricing/taxes/",
  path: "/pricing/taxes/",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingPlansIndexRoute = PricingPlansIndexRouteImport.update({
  id: "/pricing/plans/",
  path: "/pricing/plans/",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingMetricsIndexRoute = PricingMetricsIndexRouteImport.update({
  id: "/pricing/metrics/",
  path: "/pricing/metrics/",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingCouponsIndexRoute = PricingCouponsIndexRouteImport.update({
  id: "/pricing/coupons/",
  path: "/pricing/coupons/",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingAddOnsIndexRoute = PricingAddOnsIndexRouteImport.update({
  id: "/pricing/add-ons/",
  path: "/pricing/add-ons/",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingTaxesNewRoute = PricingTaxesNewRouteImport.update({
  id: "/pricing/taxes/new",
  path: "/pricing/taxes/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingTaxesIdRoute = PricingTaxesIdRouteImport.update({
  id: "/pricing/taxes/$id",
  path: "/pricing/taxes/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingPlansNewRoute = PricingPlansNewRouteImport.update({
  id: "/pricing/plans/new",
  path: "/pricing/plans/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingPlansIdRoute = PricingPlansIdRouteImport.update({
  id: "/pricing/plans/$id",
  path: "/pricing/plans/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingMetricsNewRoute = PricingMetricsNewRouteImport.update({
  id: "/pricing/metrics/new",
  path: "/pricing/metrics/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingMetricsIdRoute = PricingMetricsIdRouteImport.update({
  id: "/pricing/metrics/$id",
  path: "/pricing/metrics/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingCouponsNewRoute = PricingCouponsNewRouteImport.update({
  id: "/pricing/coupons/new",
  path: "/pricing/coupons/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingCouponsIdRoute = PricingCouponsIdRouteImport.update({
  id: "/pricing/coupons/$id",
  path: "/pricing/coupons/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingAddOnsNewRoute = PricingAddOnsNewRouteImport.update({
  id: "/pricing/add-ons/new",
  path: "/pricing/add-ons/new",
  getParentRoute: () => rootRouteImport,
} as any)
const PricingAddOnsIdRoute = PricingAddOnsIdRouteImport.update({
  id: "/pricing/add-ons/$id",
  path: "/pricing/add-ons/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/control-plane": typeof ControlPlaneRoute
  "/customer-onboarding": typeof CustomerOnboardingRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/invoice-explainability": typeof InvoiceExplainabilityRoute
  "/login": typeof LoginRoute
  "/payment-operations": typeof PaymentOperationsRoute
  "/register": typeof RegisterRoute
  "/replay-operations": typeof ReplayOperationsRoute
  "/reset-password": typeof ResetPasswordRoute
  "/usage-events": typeof UsageEventsRoute
  "/workspace-access": typeof WorkspaceAccessRoute
  "/workspace-setup": typeof WorkspaceSetupRoute
  "/customers/$externalId": typeof CustomersExternalIdRoute
  "/customers/new": typeof CustomersNewRoute
  "/dunning/$id": typeof DunningIdRoute
  "/invite/$token": typeof InviteTokenRoute
  "/invoices/$id": typeof InvoicesIdRoute
  "/payments/$id": typeof PaymentsIdRoute
  "/subscriptions/$id": typeof SubscriptionsIdRoute
  "/subscriptions/new": typeof SubscriptionsNewRoute
  "/customers/": typeof CustomersIndexRoute
  "/dunning/": typeof DunningIndexRoute
  "/invoices/": typeof InvoicesIndexRoute
  "/payments/": typeof PaymentsIndexRoute
  "/pricing/": typeof PricingIndexRoute
  "/subscriptions/": typeof SubscriptionsIndexRoute
  "/pricing/add-ons/$id": typeof PricingAddOnsIdRoute
  "/pricing/add-ons/new": typeof PricingAddOnsNewRoute
  "/pricing/coupons/$id": typeof PricingCouponsIdRoute
  "/pricing/coupons/new": typeof PricingCouponsNewRoute
  "/pricing/metrics/$id": typeof PricingMetricsIdRoute
  "/pricing/metrics/new": typeof PricingMetricsNewRoute
  "/pricing/plans/$id": typeof PricingPlansIdRoute
  "/pricing/plans/new": typeof PricingPlansNewRoute
  "/pricing/taxes/$id": typeof PricingTaxesIdRoute
  "/pricing/taxes/new": typeof PricingTaxesNewRoute
  "/pricing/add-ons/": typeof PricingAddOnsIndexRoute
  "/pricing/coupons/": typeof PricingCouponsIndexRoute
  "/pricing/metrics/": typeof PricingMetricsIndexRoute
  "/pricing/plans/": typeof PricingPlansIndexRoute
  "/pricing/taxes/": typeof PricingTaxesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/control-plane": typeof ControlPlaneRoute
  "/customer-onboarding": typeof CustomerOnboardingRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/invoice-explainability": typeof InvoiceExplainabilityRoute
  "/login": typeof LoginRoute
  "/payment-operations": typeof PaymentOperationsRoute
  "/register": typeof RegisterRoute
  "/replay-operations": typeof ReplayOperationsRoute
  "/reset-password": typeof ResetPasswordRoute
  "/usage-events": typeof UsageEventsRoute
  "/workspace-access": typeof WorkspaceAccessRoute
  "/workspace-setup": typeof WorkspaceSetupRoute
  "/customers/$externalId": typeof CustomersExternalIdRoute
  "/customers/new": typeof CustomersNewRoute
  "/dunning/$id": typeof DunningIdRoute
  "/invite/$token": typeof InviteTokenRoute
  "/invoices/$id": typeof InvoicesIdRoute
  "/payments/$id": typeof PaymentsIdRoute
  "/subscriptions/$id": typeof SubscriptionsIdRoute
  "/subscriptions/new": typeof SubscriptionsNewRoute
  "/customers": typeof CustomersIndexRoute
  "/dunning": typeof DunningIndexRoute
  "/invoices": typeof InvoicesIndexRoute
  "/payments": typeof PaymentsIndexRoute
  "/pricing": typeof PricingIndexRoute
  "/subscriptions": typeof SubscriptionsIndexRoute
  "/pricing/add-ons/$id": typeof PricingAddOnsIdRoute
  "/pricing/add-ons/new": typeof PricingAddOnsNewRoute
  "/pricing/coupons/$id": typeof PricingCouponsIdRoute
  "/pricing/coupons/new": typeof PricingCouponsNewRoute
  "/pricing/metrics/$id": typeof PricingMetricsIdRoute
  "/pricing/metrics/new": typeof PricingMetricsNewRoute
  "/pricing/plans/$id": typeof PricingPlansIdRoute
  "/pricing/plans/new": typeof PricingPlansNewRoute
  "/pricing/taxes/$id": typeof PricingTaxesIdRoute
  "/pricing/taxes/new": typeof PricingTaxesNewRoute
  "/pricing/add-ons": typeof PricingAddOnsIndexRoute
  "/pricing/coupons": typeof PricingCouponsIndexRoute
  "/pricing/metrics": typeof PricingMetricsIndexRoute
  "/pricing/plans": typeof PricingPlansIndexRoute
  "/pricing/taxes": typeof PricingTaxesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/control-plane": typeof ControlPlaneRoute
  "/customer-onboarding": typeof CustomerOnboardingRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/invoice-explainability": typeof InvoiceExplainabilityRoute
  "/login": typeof LoginRoute
  "/payment-operations": typeof PaymentOperationsRoute
  "/register": typeof RegisterRoute
  "/replay-operations": typeof ReplayOperationsRoute
  "/reset-password": typeof ResetPasswordRoute
  "/usage-events": typeof UsageEventsRoute
  "/workspace-access": typeof WorkspaceAccessRoute
  "/workspace-setup": typeof WorkspaceSetupRoute
  "/customers/$externalId": typeof CustomersExternalIdRoute
  "/customers/new": typeof CustomersNewRoute
  "/dunning/$id": typeof DunningIdRoute
  "/invite/$token": typeof InviteTokenRoute
  "/invoices/$id": typeof InvoicesIdRoute
  "/payments/$id": typeof PaymentsIdRoute
  "/subscriptions/$id": typeof SubscriptionsIdRoute
  "/subscriptions/new": typeof SubscriptionsNewRoute
  "/customers/": typeof CustomersIndexRoute
  "/dunning/": typeof DunningIndexRoute
  "/invoices/": typeof InvoicesIndexRoute
  "/payments/": typeof PaymentsIndexRoute
  "/pricing/": typeof PricingIndexRoute
  "/subscriptions/": typeof SubscriptionsIndexRoute
  "/pricing/add-ons/$id": typeof PricingAddOnsIdRoute
  "/pricing/add-ons/new": typeof PricingAddOnsNewRoute
  "/pricing/coupons/$id": typeof PricingCouponsIdRoute
  "/pricing/coupons/new": typeof PricingCouponsNewRoute
  "/pricing/metrics/$id": typeof PricingMetricsIdRoute
  "/pricing/metrics/new": typeof PricingMetricsNewRoute
  "/pricing/plans/$id": typeof PricingPlansIdRoute
  "/pricing/plans/new": typeof PricingPlansNewRoute
  "/pricing/taxes/$id": typeof PricingTaxesIdRoute
  "/pricing/taxes/new": typeof PricingTaxesNewRoute
  "/pricing/add-ons/": typeof PricingAddOnsIndexRoute
  "/pricing/coupons/": typeof PricingCouponsIndexRoute
  "/pricing/metrics/": typeof PricingMetricsIndexRoute
  "/pricing/plans/": typeof PricingPlansIndexRoute
  "/pricing/taxes/": typeof PricingTaxesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/control-plane"
    | "/customer-onboarding"
    | "/forgot-password"
    | "/invoice-explainability"
    | "/login"
    | "/payment-operations"
    | "/register"
    | "/replay-operations"
    | "/reset-password"
    | "/usage-events"
    | "/workspace-access"
    | "/workspace-setup"
    | "/customers/$externalId"
    | "/customers/new"
    | "/dunning/$id"
    | "/invite/$token"
    | "/invoices/$id"
    | "/payments/$id"
    | "/subscriptions/$id"
    | "/subscriptions/new"
    | "/customers/"
    | "/dunning/"
    | "/invoices/"
    | "/payments/"
    | "/pricing/"
    | "/subscriptions/"
    | "/pricing/add-ons/$id"
    | "/pricing/add-ons/new"
    | "/pricing/coupons/$id"
    | "/pricing/coupons/new"
    | "/pricing/metrics/$id"
    | "/pricing/metrics/new"
    | "/pricing/plans/$id"
    | "/pricing/plans/new"
    | "/pricing/taxes/$id"
    | "/pricing/taxes/new"
    | "/pricing/add-ons/"
    | "/pricing/coupons/"
    | "/pricing/metrics/"
    | "/pricing/plans/"
    | "/pricing/taxes/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/control-plane"
    | "/customer-onboarding"
    | "/forgot-password"
    | "/invoice-explainability"
    | "/login"
    | "/payment-operations"
    | "/register"
    | "/replay-operations"
    | "/reset-password"
    | "/usage-events"
    | "/workspace-access"
    | "/workspace-setup"
    | "/customers/$externalId"
    | "/customers/new"
    | "/dunning/$id"
    | "/invite/$token"
    | "/invoices/$id"
    | "/payments/$id"
    | "/subscriptions/$id"
    | "/subscriptions/new"
    | "/customers"
    | "/dunning"
    | "/invoices"
    | "/payments"
    | "/pricing"
    | "/subscriptions"
    | "/pricing/add-ons/$id"
    | "/pricing/add-ons/new"
    | "/pricing/coupons/$id"
    | "/pricing/coupons/new"
    | "/pricing/metrics/$id"
    | "/pricing/metrics/new"
    | "/pricing/plans/$id"
    | "/pricing/plans/new"
    | "/pricing/taxes/$id"
    | "/pricing/taxes/new"
    | "/pricing/add-ons"
    | "/pricing/coupons"
    | "/pricing/metrics"
    | "/pricing/plans"
    | "/pricing/taxes"
  id:
    | "__root__"
    | "/"
    | "/control-plane"
    | "/customer-onboarding"
    | "/forgot-password"
    | "/invoice-explainability"
    | "/login"
    | "/payment-operations"
    | "/register"
    | "/replay-operations"
    | "/reset-password"
    | "/usage-events"
    | "/workspace-access"
    | "/workspace-setup"
    | "/customers/$externalId"
    | "/customers/new"
    | "/dunning/$id"
    | "/invite/$token"
    | "/invoices/$id"
    | "/payments/$id"
    | "/subscriptions/$id"
    | "/subscriptions/new"
    | "/customers/"
    | "/dunning/"
    | "/invoices/"
    | "/payments/"
    | "/pricing/"
    | "/subscriptions/"
    | "/pricing/add-ons/$id"
    | "/pricing/add-ons/new"
    | "/pricing/coupons/$id"
    | "/pricing/coupons/new"
    | "/pricing/metrics/$id"
    | "/pricing/metrics/new"
    | "/pricing/plans/$id"
    | "/pricing/plans/new"
    | "/pricing/taxes/$id"
    | "/pricing/taxes/new"
    | "/pricing/add-ons/"
    | "/pricing/coupons/"
    | "/pricing/metrics/"
    | "/pricing/plans/"
    | "/pricing/taxes/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlPlaneRoute: typeof ControlPlaneRoute
  CustomerOnboardingRoute: typeof CustomerOnboardingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvoiceExplainabilityRoute: typeof InvoiceExplainabilityRoute
  LoginRoute: typeof LoginRoute
  PaymentOperationsRoute: typeof PaymentOperationsRoute
  RegisterRoute: typeof RegisterRoute
  ReplayOperationsRoute: typeof ReplayOperationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsageEventsRoute: typeof UsageEventsRoute
  WorkspaceAccessRoute: typeof WorkspaceAccessRoute
  WorkspaceSetupRoute: typeof WorkspaceSetupRoute
  CustomersExternalIdRoute: typeof CustomersExternalIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
  DunningIdRoute: typeof DunningIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  PaymentsIdRoute: typeof PaymentsIdRoute
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  SubscriptionsNewRoute: typeof SubscriptionsNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DunningIndexRoute: typeof DunningIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
  PricingAddOnsIdRoute: typeof PricingAddOnsIdRoute
  PricingAddOnsNewRoute: typeof PricingAddOnsNewRoute
  PricingCouponsIdRoute: typeof PricingCouponsIdRoute
  PricingCouponsNewRoute: typeof PricingCouponsNewRoute
  PricingMetricsIdRoute: typeof PricingMetricsIdRoute
  PricingMetricsNewRoute: typeof PricingMetricsNewRoute
  PricingPlansIdRoute: typeof PricingPlansIdRoute
  PricingPlansNewRoute: typeof PricingPlansNewRoute
  PricingTaxesIdRoute: typeof PricingTaxesIdRoute
  PricingTaxesNewRoute: typeof PricingTaxesNewRoute
  PricingAddOnsIndexRoute: typeof PricingAddOnsIndexRoute
  PricingCouponsIndexRoute: typeof PricingCouponsIndexRoute
  PricingMetricsIndexRoute: typeof PricingMetricsIndexRoute
  PricingPlansIndexRoute: typeof PricingPlansIndexRoute
  PricingTaxesIndexRoute: typeof PricingTaxesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workspace-setup": {
      id: "/workspace-setup"
      path: "/workspace-setup"
      fullPath: "/workspace-setup"
      preLoaderRoute: typeof WorkspaceSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workspace-access": {
      id: "/workspace-access"
      path: "/workspace-access"
      fullPath: "/workspace-access"
      preLoaderRoute: typeof WorkspaceAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/usage-events": {
      id: "/usage-events"
      path: "/usage-events"
      fullPath: "/usage-events"
      preLoaderRoute: typeof UsageEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/replay-operations": {
      id: "/replay-operations"
      path: "/replay-operations"
      fullPath: "/replay-operations"
      preLoaderRoute: typeof ReplayOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/payment-operations": {
      id: "/payment-operations"
      path: "/payment-operations"
      fullPath: "/payment-operations"
      preLoaderRoute: typeof PaymentOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invoice-explainability": {
      id: "/invoice-explainability"
      path: "/invoice-explainability"
      fullPath: "/invoice-explainability"
      preLoaderRoute: typeof InvoiceExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/customer-onboarding": {
      id: "/customer-onboarding"
      path: "/customer-onboarding"
      fullPath: "/customer-onboarding"
      preLoaderRoute: typeof CustomerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/control-plane": {
      id: "/control-plane"
      path: "/control-plane"
      fullPath: "/control-plane"
      preLoaderRoute: typeof ControlPlaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/subscriptions/": {
      id: "/subscriptions/"
      path: "/subscriptions"
      fullPath: "/subscriptions/"
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/": {
      id: "/pricing/"
      path: "/pricing"
      fullPath: "/pricing/"
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/payments/": {
      id: "/payments/"
      path: "/payments"
      fullPath: "/payments/"
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invoices/": {
      id: "/invoices/"
      path: "/invoices"
      fullPath: "/invoices/"
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dunning/": {
      id: "/dunning/"
      path: "/dunning"
      fullPath: "/dunning/"
      preLoaderRoute: typeof DunningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/customers/": {
      id: "/customers/"
      path: "/customers"
      fullPath: "/customers/"
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/subscriptions/new": {
      id: "/subscriptions/new"
      path: "/subscriptions/new"
      fullPath: "/subscriptions/new"
      preLoaderRoute: typeof SubscriptionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/subscriptions/$id": {
      id: "/subscriptions/$id"
      path: "/subscriptions/$id"
      fullPath: "/subscriptions/$id"
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/payments/$id": {
      id: "/payments/$id"
      path: "/payments/$id"
      fullPath: "/payments/$id"
      preLoaderRoute: typeof PaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invoices/$id": {
      id: "/invoices/$id"
      path: "/invoices/$id"
      fullPath: "/invoices/$id"
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite/$token": {
      id: "/invite/$token"
      path: "/invite/$token"
      fullPath: "/invite/$token"
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dunning/$id": {
      id: "/dunning/$id"
      path: "/dunning/$id"
      fullPath: "/dunning/$id"
      preLoaderRoute: typeof DunningIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/customers/new": {
      id: "/customers/new"
      path: "/customers/new"
      fullPath: "/customers/new"
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/customers/$externalId": {
      id: "/customers/$externalId"
      path: "/customers/$externalId"
      fullPath: "/customers/$externalId"
      preLoaderRoute: typeof CustomersExternalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/taxes/": {
      id: "/pricing/taxes/"
      path: "/pricing/taxes"
      fullPath: "/pricing/taxes/"
      preLoaderRoute: typeof PricingTaxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/plans/": {
      id: "/pricing/plans/"
      path: "/pricing/plans"
      fullPath: "/pricing/plans/"
      preLoaderRoute: typeof PricingPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/metrics/": {
      id: "/pricing/metrics/"
      path: "/pricing/metrics"
      fullPath: "/pricing/metrics/"
      preLoaderRoute: typeof PricingMetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/coupons/": {
      id: "/pricing/coupons/"
      path: "/pricing/coupons"
      fullPath: "/pricing/coupons/"
      preLoaderRoute: typeof PricingCouponsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/add-ons/": {
      id: "/pricing/add-ons/"
      path: "/pricing/add-ons"
      fullPath: "/pricing/add-ons/"
      preLoaderRoute: typeof PricingAddOnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/taxes/new": {
      id: "/pricing/taxes/new"
      path: "/pricing/taxes/new"
      fullPath: "/pricing/taxes/new"
      preLoaderRoute: typeof PricingTaxesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/taxes/$id": {
      id: "/pricing/taxes/$id"
      path: "/pricing/taxes/$id"
      fullPath: "/pricing/taxes/$id"
      preLoaderRoute: typeof PricingTaxesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/plans/new": {
      id: "/pricing/plans/new"
      path: "/pricing/plans/new"
      fullPath: "/pricing/plans/new"
      preLoaderRoute: typeof PricingPlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/plans/$id": {
      id: "/pricing/plans/$id"
      path: "/pricing/plans/$id"
      fullPath: "/pricing/plans/$id"
      preLoaderRoute: typeof PricingPlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/metrics/new": {
      id: "/pricing/metrics/new"
      path: "/pricing/metrics/new"
      fullPath: "/pricing/metrics/new"
      preLoaderRoute: typeof PricingMetricsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/metrics/$id": {
      id: "/pricing/metrics/$id"
      path: "/pricing/metrics/$id"
      fullPath: "/pricing/metrics/$id"
      preLoaderRoute: typeof PricingMetricsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/coupons/new": {
      id: "/pricing/coupons/new"
      path: "/pricing/coupons/new"
      fullPath: "/pricing/coupons/new"
      preLoaderRoute: typeof PricingCouponsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/coupons/$id": {
      id: "/pricing/coupons/$id"
      path: "/pricing/coupons/$id"
      fullPath: "/pricing/coupons/$id"
      preLoaderRoute: typeof PricingCouponsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/add-ons/new": {
      id: "/pricing/add-ons/new"
      path: "/pricing/add-ons/new"
      fullPath: "/pricing/add-ons/new"
      preLoaderRoute: typeof PricingAddOnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pricing/add-ons/$id": {
      id: "/pricing/add-ons/$id"
      path: "/pricing/add-ons/$id"
      fullPath: "/pricing/add-ons/$id"
      preLoaderRoute: typeof PricingAddOnsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlPlaneRoute: ControlPlaneRoute,
  CustomerOnboardingRoute: CustomerOnboardingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoiceExplainabilityRoute: InvoiceExplainabilityRoute,
  LoginRoute: LoginRoute,
  PaymentOperationsRoute: PaymentOperationsRoute,
  RegisterRoute: RegisterRoute,
  ReplayOperationsRoute: ReplayOperationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsageEventsRoute: UsageEventsRoute,
  WorkspaceAccessRoute: WorkspaceAccessRoute,
  WorkspaceSetupRoute: WorkspaceSetupRoute,
  CustomersExternalIdRoute: CustomersExternalIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  DunningIdRoute: DunningIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  PaymentsIdRoute: PaymentsIdRoute,
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  SubscriptionsNewRoute: SubscriptionsNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DunningIndexRoute: DunningIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
  PricingAddOnsIdRoute: PricingAddOnsIdRoute,
  PricingAddOnsNewRoute: PricingAddOnsNewRoute,
  PricingCouponsIdRoute: PricingCouponsIdRoute,
  PricingCouponsNewRoute: PricingCouponsNewRoute,
  PricingMetricsIdRoute: PricingMetricsIdRoute,
  PricingMetricsNewRoute: PricingMetricsNewRoute,
  PricingPlansIdRoute: PricingPlansIdRoute,
  PricingPlansNewRoute: PricingPlansNewRoute,
  PricingTaxesIdRoute: PricingTaxesIdRoute,
  PricingTaxesNewRoute: PricingTaxesNewRoute,
  PricingAddOnsIndexRoute: PricingAddOnsIndexRoute,
  PricingCouponsIndexRoute: PricingCouponsIndexRoute,
  PricingMetricsIndexRoute: PricingMetricsIndexRoute,
  PricingPlansIndexRoute: PricingPlansIndexRoute,
  PricingTaxesIndexRoute: PricingTaxesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
