ALTER TABLE coupons
  ADD COLUMN IF NOT EXISTS frequency TEXT NOT NULL DEFAULT 'forever',
  ADD COLUMN IF NOT EXISTS frequency_duration INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expiration_at TIMESTAMPTZ;
