api:
  replicas: 1
  image:
    repository: "139831607173.dkr.ecr.us-east-1.amazonaws.com/lago-alpha-staging/api"
    tag: "latest"
  autoscaling:
    enabled: false

replayWorker:
  enabled: true
  replicas: 1
  image:
    repository: "139831607173.dkr.ecr.us-east-1.amazonaws.com/lago-alpha-staging/api"
    tag: "latest"

replayDispatcher:
  enabled: true
  replicas: 1
  image:
    repository: "139831607173.dkr.ecr.us-east-1.amazonaws.com/lago-alpha-staging/api"
    tag: "latest"

web:
  enabled: true
  replicas: 1
  image:
    repository: "139831607173.dkr.ecr.us-east-1.amazonaws.com/lago-alpha-staging/web"
    tag: "latest"

env:
  APP_ENV: "staging"
  UI_SESSION_COOKIE_SECURE: "true"
  UI_SESSION_COOKIE_SAMESITE: "lax"
  UI_SESSION_REQUIRE_ORIGIN: "true"
  UI_SESSION_ALLOWED_ORIGINS: "https://staging.sagarwaidande.org,https://api-staging.sagarwaidande.org"

serviceAccounts:
  api:
    create: true
    name: "lago-alpha-api"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::139831607173:role/lago-alpha-staging-api-irsa"
  replayWorker:
    create: true
    name: "lago-alpha-replay-worker"
    annotations: {}
  replayDispatcher:
    create: true
    name: "lago-alpha-replay-dispatcher"
    annotations: {}
  web:
    create: true
    name: "lago-alpha-web"
    annotations: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare-prod"
  apiHost: "api-staging.sagarwaidande.org"
  webHost: "staging.sagarwaidande.org"
  tls:
    - secretName: lago-alpha-staging-tls
      hosts:
        - api-staging.sagarwaidande.org
        - staging.sagarwaidande.org

secretEnv:
  secretRefName: "lago-alpha-runtime-staging"

externalSecrets:
  enabled: true
  refreshInterval: "1m"
  runtimeSecretName: "lago-alpha/staging/runtime"
  secretStoreRef:
    kind: "ClusterSecretStore"
    name: "aws-secretsmanager"
  createClusterSecretStore: true
