package api

import (
	"net/http"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	httpRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "alpha_http_requests_total",
			Help: "Total HTTP requests by method, route, and status code.",
		},
		[]string{"method", "route", "status"},
	)

	httpRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "alpha_http_request_duration_seconds",
			Help:    "HTTP request duration in seconds.",
			Buckets: []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
		},
		[]string{"method", "route"},
	)

	authDeniedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "alpha_auth_denied_total",
			Help: "Total authentication denials by reason.",
		},
		[]string{"reason"},
	)

	rateLimitedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "alpha_rate_limited_total",
			Help: "Total rate-limited requests by policy.",
		},
		[]string{"policy"},
	)

	invoicesGeneratedTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "alpha_invoices_generated_total",
			Help: "Total invoices generated by the billing engine.",
		},
	)

	invoicesFinalizedTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "alpha_invoices_finalized_total",
			Help: "Total invoices finalized (sent to Stripe).",
		},
	)

	paymentsSucceededTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "alpha_payments_succeeded_total",
			Help: "Total payments that succeeded.",
		},
	)

	paymentsFailedTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "alpha_payments_failed_total",
			Help: "Total payments that failed.",
		},
	)

	dunningRunsActiveGauge = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "alpha_dunning_runs_active",
			Help: "Number of active dunning runs.",
		},
	)

	webhooksReceivedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "alpha_webhooks_received_total",
			Help: "Total Stripe webhooks received by event type.",
		},
		[]string{"event_type"},
	)
)

func init() {
	prometheus.MustRegister(
		httpRequestsTotal,
		httpRequestDuration,
		authDeniedTotal,
		rateLimitedTotal,
		invoicesGeneratedTotal,
		invoicesFinalizedTotal,
		paymentsSucceededTotal,
		paymentsFailedTotal,
		dunningRunsActiveGauge,
		webhooksReceivedTotal,
	)
}

func prometheusHandler() http.Handler {
	return promhttp.Handler()
}
