#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
browser_env_file="$(mktemp)"
trap 'rm -f "$browser_env_file"' EXIT

export ALPHA_API_BASE_URL="${ALPHA_API_BASE_URL:-https://api-staging.sagarwaidande.org}"
export PLAYWRIGHT_LIVE_BASE_URL="${PLAYWRIGHT_LIVE_BASE_URL:-https://staging.sagarwaidande.org}"
export PLAYWRIGHT_LIVE_API_BASE_URL="${PLAYWRIGHT_LIVE_API_BASE_URL:-$ALPHA_API_BASE_URL}"

(
  cd "$repo_root"
  PLAYWRIGHT_LIVE_BASE_URL="$PLAYWRIGHT_LIVE_BASE_URL" \
  PLAYWRIGHT_LIVE_API_BASE_URL="$PLAYWRIGHT_LIVE_API_BASE_URL" \
  bash ./scripts/bootstrap_live_e2e_browser_users_cluster.sh >"$browser_env_file"
)

# shellcheck disable=SC1090
source "$browser_env_file"

required_envs=(
  PLAYWRIGHT_LIVE_BASE_URL
  PLAYWRIGHT_LIVE_PLATFORM_EMAIL
  PLAYWRIGHT_LIVE_PLATFORM_PASSWORD
  PLAYWRIGHT_LIVE_TENANT_ID
)

for key in "${required_envs[@]}"; do
  if [[ -z "${!key:-}" ]]; then
    echo "missing required environment variable: $key" >&2
    exit 1
  fi
done

run_id="${RUN_ID:-$(date +%Y%m%d%H%M%S)-$$}"
PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_EMAIL="playwright-live-invite-admin-${run_id}@alpha.test"
PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_DISPLAY_NAME="Playwright Invite Admin ${run_id}"
PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_PASSWORD="playwright-live-invite-admin-password-${run_id}"
PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_EMAIL="playwright-live-invite-writer-${run_id}@alpha.test"
PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_DISPLAY_NAME="Playwright Invite Writer ${run_id}"
PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_PASSWORD="playwright-live-invite-writer-password-${run_id}"

(
  cd "$repo_root/web"
  PLAYWRIGHT_LIVE_BASE_URL="$PLAYWRIGHT_LIVE_BASE_URL" \
  PLAYWRIGHT_LIVE_API_BASE_URL="$PLAYWRIGHT_LIVE_API_BASE_URL" \
  PLAYWRIGHT_LIVE_PLATFORM_EMAIL="$PLAYWRIGHT_LIVE_PLATFORM_EMAIL" \
  PLAYWRIGHT_LIVE_PLATFORM_PASSWORD="$PLAYWRIGHT_LIVE_PLATFORM_PASSWORD" \
  PLAYWRIGHT_LIVE_TENANT_ID="$PLAYWRIGHT_LIVE_TENANT_ID" \
  PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_EMAIL="$PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_EMAIL" \
  PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_DISPLAY_NAME="$PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_DISPLAY_NAME" \
  PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_PASSWORD="$PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_PASSWORD" \
  PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_EMAIL="$PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_EMAIL" \
  PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_DISPLAY_NAME="$PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_DISPLAY_NAME" \
  PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_PASSWORD="$PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_PASSWORD" \
  npx -y pnpm@10.30.0 exec playwright install --with-deps chromium

  PLAYWRIGHT_LIVE_BASE_URL="$PLAYWRIGHT_LIVE_BASE_URL" \
  PLAYWRIGHT_LIVE_API_BASE_URL="$PLAYWRIGHT_LIVE_API_BASE_URL" \
  PLAYWRIGHT_LIVE_PLATFORM_EMAIL="$PLAYWRIGHT_LIVE_PLATFORM_EMAIL" \
  PLAYWRIGHT_LIVE_PLATFORM_PASSWORD="$PLAYWRIGHT_LIVE_PLATFORM_PASSWORD" \
  PLAYWRIGHT_LIVE_TENANT_ID="$PLAYWRIGHT_LIVE_TENANT_ID" \
  PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_EMAIL="$PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_EMAIL" \
  PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_DISPLAY_NAME="$PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_DISPLAY_NAME" \
  PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_PASSWORD="$PLAYWRIGHT_LIVE_ACCESS_ADMIN_INVITE_PASSWORD" \
  PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_EMAIL="$PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_EMAIL" \
  PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_DISPLAY_NAME="$PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_DISPLAY_NAME" \
  PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_PASSWORD="$PLAYWRIGHT_LIVE_ACCESS_WRITER_INVITE_PASSWORD" \
  npx -y pnpm@10.30.0 exec playwright test tests/e2e/access-invite-live.spec.ts --workers=1
)
