/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WorkspaceSetupRouteImport } from "./routes/workspace-setup"
import { Route as WorkspaceAccessRouteImport } from "./routes/workspace-access"
import { Route as UsageEventsRouteImport } from "./routes/usage-events"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as ReplayOperationsRouteImport } from "./routes/replay-operations"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as PaymentOperationsRouteImport } from "./routes/payment-operations"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as InvoiceExplainabilityRouteImport } from "./routes/invoice-explainability"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as CustomerOnboardingRouteImport } from "./routes/customer-onboarding"
import { Route as ControlPlaneRouteImport } from "./routes/control-plane"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SubscriptionsIndexRouteImport } from "./routes/subscriptions/index"
import { Route as PricingIndexRouteImport } from "./routes/pricing/index"
import { Route as PaymentsIndexRouteImport } from "./routes/payments/index"
import { Route as InvoicesIndexRouteImport } from "./routes/invoices/index"
import { Route as DunningIndexRouteImport } from "./routes/dunning/index"
import { Route as CustomersIndexRouteImport } from "./routes/customers/index"
import { Route as SubscriptionsNewRouteImport } from "./routes/subscriptions/new"
import { Route as SubscriptionsIdRouteImport } from "./routes/subscriptions/$id"
import { Route as PaymentsIdRouteImport } from "./routes/payments/$id"
import { Route as InvoicesIdRouteImport } from "./routes/invoices/$id"
import { Route as InviteTokenRouteImport } from "./routes/invite/$token"
import { Route as DunningIdRouteImport } from "./routes/dunning/$id"
import { Route as CustomersNewRouteImport } from "./routes/customers/new"
import { Route as CustomersExternalIdRouteImport } from "./routes/customers/$externalId"
import { Route as PricingTaxesIndexRouteImport } from "./routes/pricing/taxes/index"
import { Route as PricingPlansIndexRouteImport } from "./routes/pricing/plans/index"
import { Route as PricingMetricsIndexRouteImport } from "./routes/pricing/metrics/index"
import { Route as PricingCouponsIndexRouteImport } from "./routes/pricing/coupons/index"
import { Route as PricingAddOnsIndexRouteImport } from "./routes/pricing/add-ons/index"
import { Route as PricingTaxesNewRouteImport } from "./routes/pricing/taxes/new"
import { Route as PricingTaxesIdRouteImport } from "./routes/pricing/taxes/$id"
import { Route as PricingPlansNewRouteImport } from "./routes/pricing/plans/new"
import { Route as PricingPlansIdRouteImport } from "./routes/pricing/plans/$id"
import { Route as PricingMetricsNewRouteImport } from "./routes/pricing/metrics/new"
import { Route as PricingMetricsIdRouteImport } from "./routes/pricing/metrics/$id"
import { Route as PricingCouponsNewRouteImport } from "./routes/pricing/coupons/new"
import { Route as PricingCouponsIdRouteImport } from "./routes/pricing/coupons/$id"
import { Route as PricingAddOnsNewRouteImport } from "./routes/pricing/add-ons/new"
import { Route as PricingAddOnsIdRouteImport } from "./routes/pricing/add-ons/$id"

const WorkspaceSetupRoute = WorkspaceSetupRouteImport.update({
  id: "/workspace-setup",
  path: "/workspace-setup",
  getParentRoute: () => rootRouteImport,
})
const WorkspaceAccessRoute = WorkspaceAccessRouteImport.update({
  id: "/workspace-access",
  path: "/workspace-access",
  getParentRoute: () => rootRouteImport,
})
const UsageEventsRoute = UsageEventsRouteImport.update({
  id: "/usage-events",
  path: "/usage-events",
  getParentRoute: () => rootRouteImport,
})
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
})
const ReplayOperationsRoute = ReplayOperationsRouteImport.update({
  id: "/replay-operations",
  path: "/replay-operations",
  getParentRoute: () => rootRouteImport,
})
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
})
const PaymentOperationsRoute = PaymentOperationsRouteImport.update({
  id: "/payment-operations",
  path: "/payment-operations",
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
})
const InvoiceExplainabilityRoute = InvoiceExplainabilityRouteImport.update({
  id: "/invoice-explainability",
  path: "/invoice-explainability",
  getParentRoute: () => rootRouteImport,
})
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
})
const CustomerOnboardingRoute = CustomerOnboardingRouteImport.update({
  id: "/customer-onboarding",
  path: "/customer-onboarding",
  getParentRoute: () => rootRouteImport,
})
const ControlPlaneRoute = ControlPlaneRouteImport.update({
  id: "/control-plane",
  path: "/control-plane",
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
})
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: "/subscriptions/",
  path: "/subscriptions/",
  getParentRoute: () => rootRouteImport,
})
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: "/pricing/",
  path: "/pricing/",
  getParentRoute: () => rootRouteImport,
})
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: "/payments/",
  path: "/payments/",
  getParentRoute: () => rootRouteImport,
})
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: "/invoices/",
  path: "/invoices/",
  getParentRoute: () => rootRouteImport,
})
const DunningIndexRoute = DunningIndexRouteImport.update({
  id: "/dunning/",
  path: "/dunning/",
  getParentRoute: () => rootRouteImport,
})
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: "/customers/",
  path: "/customers/",
  getParentRoute: () => rootRouteImport,
})
const SubscriptionsNewRoute = SubscriptionsNewRouteImport.update({
  id: "/subscriptions/new",
  path: "/subscriptions/new",
  getParentRoute: () => rootRouteImport,
})
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: "/subscriptions/$id",
  path: "/subscriptions/$id",
  getParentRoute: () => rootRouteImport,
})
const PaymentsIdRoute = PaymentsIdRouteImport.update({
  id: "/payments/$id",
  path: "/payments/$id",
  getParentRoute: () => rootRouteImport,
})
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: "/invoices/$id",
  path: "/invoices/$id",
  getParentRoute: () => rootRouteImport,
})
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
})
const DunningIdRoute = DunningIdRouteImport.update({
  id: "/dunning/$id",
  path: "/dunning/$id",
  getParentRoute: () => rootRouteImport,
})
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: "/customers/new",
  path: "/customers/new",
  getParentRoute: () => rootRouteImport,
})
const CustomersExternalIdRoute = CustomersExternalIdRouteImport.update({
  id: "/customers/$externalId",
  path: "/customers/$externalId",
  getParentRoute: () => rootRouteImport,
})
const PricingTaxesIndexRoute = PricingTaxesIndexRouteImport.update({
  id: "/pricing/taxes/",
  path: "/pricing/taxes/",
  getParentRoute: () => rootRouteImport,
})
const PricingPlansIndexRoute = PricingPlansIndexRouteImport.update({
  id: "/pricing/plans/",
  path: "/pricing/plans/",
  getParentRoute: () => rootRouteImport,
})
const PricingMetricsIndexRoute = PricingMetricsIndexRouteImport.update({
  id: "/pricing/metrics/",
  path: "/pricing/metrics/",
  getParentRoute: () => rootRouteImport,
})
const PricingCouponsIndexRoute = PricingCouponsIndexRouteImport.update({
  id: "/pricing/coupons/",
  path: "/pricing/coupons/",
  getParentRoute: () => rootRouteImport,
})
const PricingAddOnsIndexRoute = PricingAddOnsIndexRouteImport.update({
  id: "/pricing/add-ons/",
  path: "/pricing/add-ons/",
  getParentRoute: () => rootRouteImport,
})
const PricingTaxesNewRoute = PricingTaxesNewRouteImport.update({
  id: "/pricing/taxes/new",
  path: "/pricing/taxes/new",
  getParentRoute: () => rootRouteImport,
})
const PricingTaxesIdRoute = PricingTaxesIdRouteImport.update({
  id: "/pricing/taxes/$id",
  path: "/pricing/taxes/$id",
  getParentRoute: () => rootRouteImport,
})
const PricingPlansNewRoute = PricingPlansNewRouteImport.update({
  id: "/pricing/plans/new",
  path: "/pricing/plans/new",
  getParentRoute: () => rootRouteImport,
})
const PricingPlansIdRoute = PricingPlansIdRouteImport.update({
  id: "/pricing/plans/$id",
  path: "/pricing/plans/$id",
  getParentRoute: () => rootRouteImport,
})
const PricingMetricsNewRoute = PricingMetricsNewRouteImport.update({
  id: "/pricing/metrics/new",
  path: "/pricing/metrics/new",
  getParentRoute: () => rootRouteImport,
})
const PricingMetricsIdRoute = PricingMetricsIdRouteImport.update({
  id: "/pricing/metrics/$id",
  path: "/pricing/metrics/$id",
  getParentRoute: () => rootRouteImport,
})
const PricingCouponsNewRoute = PricingCouponsNewRouteImport.update({
  id: "/pricing/coupons/new",
  path: "/pricing/coupons/new",
  getParentRoute: () => rootRouteImport,
})
const PricingCouponsIdRoute = PricingCouponsIdRouteImport.update({
  id: "/pricing/coupons/$id",
  path: "/pricing/coupons/$id",
  getParentRoute: () => rootRouteImport,
})
const PricingAddOnsNewRoute = PricingAddOnsNewRouteImport.update({
  id: "/pricing/add-ons/new",
  path: "/pricing/add-ons/new",
  getParentRoute: () => rootRouteImport,
})
const PricingAddOnsIdRoute = PricingAddOnsIdRouteImport.update({
  id: "/pricing/add-ons/$id",
  path: "/pricing/add-ons/$id",
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlPlaneRoute: ControlPlaneRoute,
  CustomerOnboardingRoute: CustomerOnboardingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoiceExplainabilityRoute: InvoiceExplainabilityRoute,
  LoginRoute: LoginRoute,
  PaymentOperationsRoute: PaymentOperationsRoute,
  RegisterRoute: RegisterRoute,
  ReplayOperationsRoute: ReplayOperationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsageEventsRoute: UsageEventsRoute,
  WorkspaceAccessRoute: WorkspaceAccessRoute,
  WorkspaceSetupRoute: WorkspaceSetupRoute,
  CustomersExternalIdRoute: CustomersExternalIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  DunningIdRoute: DunningIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  PaymentsIdRoute: PaymentsIdRoute,
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  SubscriptionsNewRoute: SubscriptionsNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DunningIndexRoute: DunningIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
  PricingAddOnsIdRoute: PricingAddOnsIdRoute,
  PricingAddOnsNewRoute: PricingAddOnsNewRoute,
  PricingCouponsIdRoute: PricingCouponsIdRoute,
  PricingCouponsNewRoute: PricingCouponsNewRoute,
  PricingMetricsIdRoute: PricingMetricsIdRoute,
  PricingMetricsNewRoute: PricingMetricsNewRoute,
  PricingPlansIdRoute: PricingPlansIdRoute,
  PricingPlansNewRoute: PricingPlansNewRoute,
  PricingTaxesIdRoute: PricingTaxesIdRoute,
  PricingTaxesNewRoute: PricingTaxesNewRoute,
  PricingAddOnsIndexRoute: PricingAddOnsIndexRoute,
  PricingCouponsIndexRoute: PricingCouponsIndexRoute,
  PricingMetricsIndexRoute: PricingMetricsIndexRoute,
  PricingPlansIndexRoute: PricingPlansIndexRoute,
  PricingTaxesIndexRoute: PricingTaxesIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
