{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.createClusterSecretStore }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStore.name }}
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.clusterSecretStore.awsRegion | quote }}
      {{- if .Values.externalSecrets.clusterSecretStore.roleArn }}
      role: {{ .Values.externalSecrets.clusterSecretStore.roleArn | quote }}
      {{- end }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.clusterSecretStore.serviceAccountName | quote }}
            namespace: {{ .Values.externalSecrets.clusterSecretStore.serviceAccountNamespace | quote }}
{{- end }}
