{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lago-alpha.fullname" . }}-web
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "lago-alpha.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "lago-alpha.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "lago-alpha.serviceAccountName.web" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          {{- $apiBaseURL := .Values.web.apiBaseURL }}
          {{- if and (not $apiBaseURL) .Values.ingress.apiHost }}
          {{- $apiBaseURL = printf "https://%s" .Values.ingress.apiHost }}
          {{- end }}
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: {{ $apiBaseURL | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
