{{- if .Values.billingConnectionCheckScheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lago-alpha.fullname" . }}-billing-connection-check-scheduler
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
    app.kubernetes.io/component: billing-connection-check-scheduler
spec:
  replicas: {{ .Values.billingConnectionCheckScheduler.replicas }}
  selector:
    matchLabels:
      {{- include "lago-alpha.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: billing-connection-check-scheduler
  template:
    metadata:
      labels:
        {{- include "lago-alpha.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: billing-connection-check-scheduler
        {{- with .Values.billingConnectionCheckScheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.billingConnectionCheckScheduler.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "lago-alpha.serviceAccountName.billingConnectionCheckScheduler" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: billing-connection-check-scheduler
          image: "{{ default .Values.api.image.repository .Values.billingConnectionCheckScheduler.image.repository }}:{{ default .Values.api.image.tag .Values.billingConnectionCheckScheduler.image.tag }}"
          imagePullPolicy: {{ .Values.billingConnectionCheckScheduler.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "lago-alpha.fullname" . }}-env
            - secretRef:
                name: {{ .Values.secretEnv.secretRefName }}
          env:
            - name: RUN_API_SERVER
              value: "false"
            - name: RUN_REPLAY_WORKER
              value: "false"
            - name: RUN_REPLAY_DISPATCHER
              value: "false"
            - name: RUN_BILLING_CONNECTION_CHECK_WORKER
              value: "false"
            - name: RUN_BILLING_CONNECTION_CHECK_SCHEDULER
              value: "true"
            - name: RUN_PAYMENT_RECONCILE_WORKER
              value: "false"
            - name: RUN_PAYMENT_RECONCILE_SCHEDULER
              value: "false"
            - name: RUN_DUNNING_WORKER
              value: "false"
            - name: RUN_DUNNING_SCHEDULER
              value: "false"
          resources:
            {{- toYaml .Values.billingConnectionCheckScheduler.resources | nindent 12 }}
{{- end }}
