{{- if .Values.billingConnectionCheckWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lago-alpha.fullname" . }}-billing-connection-check-worker
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
    app.kubernetes.io/component: billing-connection-check-worker
spec:
  replicas: {{ .Values.billingConnectionCheckWorker.replicas }}
  selector:
    matchLabels:
      {{- include "lago-alpha.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: billing-connection-check-worker
  template:
    metadata:
      labels:
        {{- include "lago-alpha.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: billing-connection-check-worker
        {{- with .Values.billingConnectionCheckWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.billingConnectionCheckWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "lago-alpha.serviceAccountName.billingConnectionCheckWorker" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: billing-connection-check-worker
          image: "{{ default .Values.api.image.repository .Values.billingConnectionCheckWorker.image.repository }}:{{ default .Values.api.image.tag .Values.billingConnectionCheckWorker.image.tag }}"
          imagePullPolicy: {{ .Values.billingConnectionCheckWorker.image.pullPolicy }}
          {{- include "lago-alpha.runtimeEnvFrom" . | nindent 10 }}
          env:
            - name: RUN_API_SERVER
              value: "false"
            - name: RUN_REPLAY_WORKER
              value: "false"
            - name: RUN_REPLAY_DISPATCHER
              value: "false"
            - name: RUN_BILLING_CONNECTION_CHECK_WORKER
              value: "true"
            - name: RUN_BILLING_CONNECTION_CHECK_SCHEDULER
              value: "false"
            - name: RUN_PAYMENT_RECONCILE_WORKER
              value: "false"
            - name: RUN_PAYMENT_RECONCILE_SCHEDULER
              value: "false"
            - name: RUN_DUNNING_WORKER
              value: "false"
            - name: RUN_DUNNING_SCHEDULER
              value: "false"
          resources:
            {{- toYaml .Values.billingConnectionCheckWorker.resources | nindent 12 }}
{{- end }}
