{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lago-alpha.fullname" . }}-migrate
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.migrations.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "lago-alpha.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "lago-alpha.serviceAccountName.api" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: "{{ default .Values.api.image.repository .Values.migrations.image.repository }}:{{ default .Values.api.image.tag .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          command: ["/app/migrate"]
          envFrom:
            - configMapRef:
                name: {{ include "lago-alpha.fullname" . }}-env
            - secretRef:
                name: {{ .Values.secretEnv.secretRefName }}
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
{{- end }}
