{{- if .Values.serviceAccounts.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lago-alpha.serviceAccountName.api" . }}
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccounts.replayWorker.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lago-alpha.serviceAccountName.replayWorker" . }}
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.replayWorker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccounts.replayDispatcher.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lago-alpha.serviceAccountName.replayDispatcher" . }}
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.replayDispatcher.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccounts.web.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lago-alpha.serviceAccountName.web" . }}
  labels:
    {{- include "lago-alpha.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
